Added diningCommonMenuItem entity and repository file to the project
ucsb-cs156-f22/team02-f22-5pm-2 pull request #34
Opened 2022-10-26 21:35 UTC by hauntedghosts

Closes Issue #30 on Kanban Board ([Create database table for UCSBDiningCommonsMenuItem](https://github.com/ucsb-cs156-f22/team02-f22-5pm-2/issues/30). CommonMenuItem entity and repository file created.

2022-10-27 00:15 UTC, bhuang01 approved these changes
LGTM

2022-10-27 00:15 UTC, eduglt requested changes
I have some feedback on the `private long id` variable in the entity class, and I think the repository interface should use `Long` instead of `String` for the primary key type.  All else LGTM!

2022-10-27 00:15 UTC, eduglt commented on src/main/java/edu/ucsb/cs156/example/entities/UCSBDiningCommonsMenuItem.java
> +    @Id
I think the `@Id` also needs
```
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
private long id;
```

2022-10-27 00:15 UTC, eduglt commented on src/main/java/edu/ucsb/cs156/example/repositories/UCSBDiningCommonsMenuItemRepository.java
> +public interface UCSBDiningCommonsMenuItemRepository extends CrudRepository<UCSBDiningCommonsMenuItem, String> {
I think the CrudRepository needs `Long` type since the primary key is a `long` not `String`.

2022-10-27 00:41 UTC, sophiacheng01 approved these changes
LGTM

2022-10-28 00:48 UTC, whugimy approved these changes
LGTM

2022-10-28 00:48 UTC, merged