sc - adding entity and repository
ucsb-cs156-f22/team02-f22-5pm-2 pull request #35
Opened 2022-10-26 23:01 UTC by sophiacheng01

In this PR we add a database to the Spring backend capable of storing menu item reviews. This PR adds the required Entity and Repository classes.

Closes #15

2022-10-26 23:41 UTC, hauntedghosts approved these changes
LGTM, just one slight change which might not matter.

2022-10-26 23:41 UTC, hauntedghosts commented on src/main/java/edu/ucsb/cs156/example/entities/MenuItemReview.java
> +  private String comments;
Maybe the order of Reviews and comments should be switched. In the documentation it seems that the dateReviewed column comes before comments.

2022-10-27 00:16 UTC, bhuang01 approved these changes
LGTM

2022-10-27 00:20 UTC, eduglt requested changes
LGTM, but I think that the MenuItemReview class is missing the `LocalDateTime dateReviewed` column.  I think it requires an import, can check Bryan's entity class for how he did it.

2022-10-27 00:22 UTC, eduglt approved these changes

2022-10-27 00:43 UTC, dengkevin approved these changes
LGTM

2022-10-28 00:43 UTC, whugimy approved these changes
LGTM

2022-10-28 00:44 UTC, merged